# https://github.com/marketplace/actions/create-a-release
name: Build and Release for awscli v1
on:
  push:
    tags:
      - "1.*"
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      BUILD_CTX: v1
      BUILD_PLATFORMS: linux/amd64,linux/arm64
    steps:
      - name: Extract tag
        id: tag
        run: echo ::set-output name=TAG_NAME::${GITHUB_REF#refs/tags/}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: cheyilin
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to quay.io
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: cheyilin+github_actions
          password: ${{ secrets.QUAY_ROBOT_TOKEN }}
      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: ${{ env.BUILD_CTX }}
          platforms: ${{ env.BUILD_PLATFORMS }}
          push: true
          cache-from: type=registry,ref=cheyilin/docker-awscli:${{ env.BUILD_CTX }}
          cache-to: type=inline
          tags: |
            cheyilin/docker-awscli:${{ env.BUILD_CTX }}
            cheyilin/docker-awscli:${{ steps.tag.outputs.TAG_NAME }}
            quay.io/cheyilin/docker-awscli:${{ steps.tag.outputs.TAG_NAME }}
