# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
name: CI for awscli v2
on:
  push:
    tags:
      - "2.*"
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      BUILD_CTX: v2
      BUILD_PLATFORMS: linux/amd64,linux/arm64
    steps:
      - name: Extract tag
        id: tag
        run: echo ::set-output name=TAG_NAME::${GITHUB_REF#refs/tags/}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Login to quay.io
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_ROBOT_USERNAME }}
          password: ${{ secrets.QUAY_ROBOT_TOKEN }}
      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: ${{ env.BUILD_CTX }}
          platforms: ${{ env.BUILD_PLATFORMS }}
          push: true
          cache-from: type=registry,ref=ghcr.io/cheyilin/docker-awscli:${{ env.BUILD_CTX }}
          cache-to: type=inline
          # disable pushing to quay.io due to Buildx bug: https://github.com/docker/buildx/issues/327
          # add line below back to `tags` to enable it again
          # quay.io/cheyilin/docker-awscli:${{ steps.tag.outputs.TAG_NAME }}
          tags: |
            ghcr.io/cheyilin/docker-awscli:${{ env.BUILD_CTX }}
            ghcr.io/cheyilin/docker-awscli:${{ steps.tag.outputs.TAG_NAME }}
            cheyilin/docker-awscli:${{ steps.tag.outputs.TAG_NAME }}
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            ## GitHub Container Registry

            https://ghcr.io/cheyilin/docker-awscli

            ```text
            ghcr.io/cheyilin/docker-awscli:${{ steps.tag.outputs.TAG_NAME }}
            ```

            ## Docker Hub

            https://hub.docker.com/r/cheyilin/docker-awscli

            ```text
            cheyilin/docker-awscli:${{ steps.tag.outputs.TAG_NAME }}
            ```
