# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
name: dev
on:
  push:
    branches:
      - master
    tags-ignore:
      - "*"
    paths-ignore:
      - README.md
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - ctx: v1
            version: "1.21.2"
          - ctx: v2
            version: "2.3.0"
    env:
      BUILD_PLATFORMS: linux/amd64,linux/arm64
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Docker Metadata
        id: meta
        uses: docker/metadata-action@v3
        # https://github.com/docker/metadata-action
        with:
          images: |
            localhost:5000/cheyilin/docker-awscli
          tags: |
            type=raw,value=${{ matrix.ctx }}
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: ${{ env.BUILD_PLATFORMS }}
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          driver-opts: network=host
      - name: Build and Push
        uses: docker/build-push-action@v2
        # https://github.com/docker/build-push-action
        with:
          context: ${{ matrix.ctx }}
          platforms: ${{ env.BUILD_PLATFORMS }}
          build-args: |
            AWS_CLI_VERSION=${{ matrix.version }}
          push: true
          cache-from: type=gha,scope=${{ matrix.ctx }}
          cache-to: type=gha,scope=${{ matrix.ctx }},mode=max
          labels: ${{ steps.meta.outputs.labels }}
          tags: |
            ${{ steps.meta.outputs.tags }}
      - name: Inspect Image
        run: |
          docker buildx imagetools inspect ${{ steps.meta.outputs.tags }}
      - name: Test Preflight
        run: |
          docker network create dind
          docker run -d --privileged \
            --network=dind --network-alias=docker -e DOCKER_TLS_CERTDIR= docker:20.10-dind
          docker run --network=dind praqma/network-multitool \
            sh -c 'until curl -sL -I docker:2375/_ping; do echo "* Wait for dockerd to be ready ..."; sleep 3; done'
      - name: Test (linux/amd64)
        run: |
          CMD="docker run --platform=linux/amd64 --network=dind ${{ steps.meta.outputs.tags }}"
          ${CMD} docker version
          ${CMD} aws --version
      - name: Test (linux/arm64)
        run: |
          CMD="docker run --platform=linux/arm64 --network=dind ${{ steps.meta.outputs.tags }}"
          ${CMD} docker version
          ${CMD} aws --version
