# https://github.com/marketplace/actions/create-a-release
name: Release
on:
  push:
    tags:
      - "*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: tag
        run: echo ::set-output name=TAG_NAME::${GITHUB_REF#refs/tags/}
      - uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: |
            ## Docker Hub

            ```text
            cheyilin/docker-awscli:${{ steps.tag.outputs.TAG_NAME }}
            ```

            ## Quay

            ```text
            quay.io/cheyilin/docker-awscli:${{ steps.tag.outputs.TAG_NAME }}
            ```
