# https://github.com/marketplace/actions/create-a-release
name: Release
on:
  push:
    tags:
      - "*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout source
        uses: actions/checkout@v2
      - name: create release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: |
            ## Images

            ### Docker Hub

            ```sh
            docker pull cheyilin/docker-awscli:${{ github.ref }}
            ```

            ### Quay

            ```sh
            docker pull quay.io/cheyilin/docker-awscli:${{ github.ref }}
            ```
