# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
name: v1
on:
  push:
    tags:
      - "1.*"
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      BUILD_CTX: v1
      BUILD_PLATFORMS: linux/amd64,linux/arm64
    steps:
      - name: Setup Envs
        run: echo BUILD_TAG=${GITHUB_REF#refs/tags/} >> $GITHUB_ENV
      - name: Checkout
        uses: actions/checkout@v2
      - name: Docker Metadata
        id: meta
        uses: docker/metadata-action@v3
        # https://github.com/docker/metadata-action
        with:
          images: |
            ghcr.io/cheyilin/docker-awscli
            cheyilin/docker-awscli
          tags: |
            type=semver,pattern={{version}}
            type=raw,value=${{ env.BUILD_CTX }}
          flavor: |
            latest=false
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: ${{ env.BUILD_PLATFORMS }}
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and Push
        uses: docker/build-push-action@v2
        # https://github.com/docker/build-push-action
        with:
          context: ${{ env.BUILD_CTX }}
          platforms: ${{ env.BUILD_PLATFORMS }}
          build-args: |
            AWS_CLI_VERSION=${{ env.BUILD_TAG }}
          push: true
          cache-from: type=registry,ref=ghcr.io/cheyilin/docker-awscli:${{ env.BUILD_CTX }}
          cache-to: type=inline
          labels: ${{ steps.meta.outputs.labels }}
          tags: |
            ${{ steps.meta.outputs.tags }}
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            ## GitHub Container Registry

            https://ghcr.io/cheyilin/docker-awscli

            ```text
            ghcr.io/cheyilin/docker-awscli:${{ env.BUILD_TAG }}
            ```

            ## Docker Hub

            https://hub.docker.com/r/cheyilin/docker-awscli

            ```text
            cheyilin/docker-awscli:${{ env.BUILD_TAG }}
            ```
